// Precomputes the land outline used by the Hero map so the browser ships
// a static SVG path instead of topojson + d3-geo.
// Run: npm run build:world
import { readFile, writeFile } from 'node:fs/promises';
import { feature } from 'topojson-client';
import { geoEquirectangular, geoPath } from 'd3-geo';

export const WIDTH = 1000;
export const HEIGHT = 500;

const topo = JSON.parse(
  await readFile(new URL('../node_modules/world-atlas/land-110m.json', import.meta.url)),
);
const land = feature(topo, topo.objects.land);
// Clip Antarctica: it adds bulk without carrying any routes.
land.features = land.features.map((f) => ({
  ...f,
  geometry: {
    ...f.geometry,
    coordinates: f.geometry.coordinates.filter((poly) => poly[0].some(([, lat]) => lat > -60)),
  },
}));

const projection = geoEquirectangular()
  .scale(WIDTH / (2 * Math.PI))
  .translate([WIDTH / 2, HEIGHT / 2]);
const path = geoPath(projection).digits(1);

const d = path(land);
const out = `// Generated by scripts/build-world.mjs. Do not edit by hand.
// Equirectangular projection, viewBox 0 0 ${WIDTH} ${HEIGHT}.
export const WORLD_VIEWBOX = { width: ${WIDTH}, height: ${HEIGHT} } as const;
export const LAND_PATH = ${JSON.stringify(d)};
`;
await writeFile(new URL('../src/assets/world-land.ts', import.meta.url), out);
console.log(`world-land.ts written (${(d.length / 1024).toFixed(1)} KB path)`);
